### ISSUE TITLE
segmentation fault (core dumped)

### ISSUE THREAD

**Issue by thomas992** [MobSlicer152/purpl-engine#1]
after compiling it on AlmaLinux 9 and launching the launcher I get the above error.
steps used to install on AlmaLinux

```
sudo dnf install gcc gcc-c++ openssl-devel bzip2-devel libffi-devel zlib-devel make -y
sudo dnf install vulkan-loader-devel

https://github.com/Kitware/CMake
download cmake from github
sudo ./bootstrap
sudo make install

https://vulkan.lunarg.com/sdk/home#linux
download SDK tarball
./vulkansdk
```

**Comment by thomas992** [comment]
![SplashScreen](https://user-images.githubusercontent.com/31554741/182070541-d41fc77d-7b0e-4446-ba73-23e4b4074416.png)
I have not even compiled it on Windows I am just kind of assuming it is going to work. Looking at the code I am a huge fan of the way you assembled this together.
![Logo](https://user-images.githubusercontent.com/31554741/182070698-665fa63c-25d0-449d-ac49-8d0b12308510.png)
I think the background should be transparent without a cascading style border-radius, zoomed in as much as possible.

**Comment by MobSlicer152** [comment]
Thanks for liking my project. It's inspired by Quake 2 and Source engine because I've had a lot of fun messing around with those engines.

**Comment by MobSlicer152** [comment]
This segfault seems to have been caused by improper usage of vsnprintf, it has been fixed.
