### ISSUE TITLE
Doxygen Comments

### ISSUE THREAD

**Issue by thomas992** [MobSlicer152/purpl-engine#10]
Doxygen has an extension on Visual Studio Code, where you write /** and press enter and it generates a lot of the documentation for you.

```C
/**
 * @brief Debug messenger callback
 * 
 * @param severity 
 * @param types 
 * @param data 
 * @param user 
 * @return VkBool32 
 */
static VkBool32 VKAPI_CALL debug_messenger_callback(VkDebugUtilsMessageSeverityFlagBitsEXT severity,
						    VkDebugUtilsMessageTypeFlagsEXT types,
						    const VkDebugUtilsMessengerCallbackDataEXT *data, void *user)
```
```C
// Debug messenger callback

static VkBool32 VKAPI_CALL debug_messenger_callback(VkDebugUtilsMessageSeverityFlagBitsEXT severity,
						    VkDebugUtilsMessageTypeFlagsEXT types,
						    const VkDebugUtilsMessengerCallbackDataEXT *data, void *user)
```
Something like the first would be better practice for generating documentation into markdown.

**Comment by MobSlicer152** [comment]
A few months ago I tried messing with that, but every single program I tried to generate documentation with refused to work. Doxygen either takes a ton of configuration or comments I don't like the look of. I've started just putting comments that just say what the function does, and the code is right there if the comment doesn't cover it.

**Comment by thomas992** [comment]
I tried using Doxygen and could not get it to work either but the VS Code extension still produces code that is suitable for documentation generators which could be utilized later. It also produces tooltips for users with the Doxygen extension (which is included in the popular C/C++ Extension Pack) [vscode screenshot showing documentation tooltip](https://live.staticflickr.com/65535/52261877846_1a14742985_b.jpg)

Programming is essentially enveloping off of larger algorithms. Documentation allows people to mentally process algorithms, with variable types, a more simple format for something that is traditionally walled by understanding.
