### ISSUE TITLE
WebGPU, Dawn

### ISSUE THREAD

**Issue by thomas992** [MobSlicer152/purpl-engine#7]
https://github.com/samdauwe/webgpu-native-examples

I want to support WebGPU which would have to be powered by [Dawn](https://dawn.googlesource.com/dawn) which is what Google Chrome will use. I was going to conduct some experiments with Dawn before proceeding with Purpl.

**Comment by MobSlicer152** [comment]
WebGPU does look interesting and would save time, so I might look into it.

**Comment by thomas992** [comment]
https://github.com/open-goal/jak-project/blob/master/goal_src/jak1/pc/pckernel.gc

OpenGoal is a project reviving the Goal programming language developed by NaughtyDog for their game which is credited with being one of the first 3d games without loading screens.

**Comment by thomas992** [comment]
Looking into WebAssembly, it looks like Zig is better supporter than Lisp and there is a game engine for Zig with Dawn already.
https://github.com/michal-z/zig-gamedev
