### ISSUE TITLE
comments

### ISSUE THREAD

**Issue by thomas992** [MobSlicer152/purpl-engine#9]
[screenshot of cpu cores](https://live.staticflickr.com/65535/52261731413_7b62e73a0a_b.jpg)

It seems like the engine maxes out a single core, and when it is changing to another core uses more power from all cores than it would from one. I thought the splash screen was suppose to appear. I am unsure how to see anything on the screen yet but I am getting excited.

launcher/main.c

```
	engine_dll_t *engine;
	//	dll_t *client;
	//	dll_t *server;
	int32_t i;
	char *arg;
	bool error;
	bool devmode;
	char *basedir;
	char *bindir;
	char *coredir;
	char *gamedir;
```
could you provide some additional context here on what a coredir and a gamedir consists of. 

in core.ini
```
there're
```
not a proper conjugation I would just write 'of'

```
[data]
; dir means a real directory, pack means a pack file. Can have as many of each as needed.
```
instead of 'read' describe it as relative because the path is of interest. 'pack means a pack file. Can have as many of each as needed.' this should be a single sentence, separate from the first.
```
; Basic details of the game
```
Basic details would imply a more verbal description of something than a configuration file would have.

```
; Configuration of Purpl Manifest
```
probably not the word manifest. Still unsure how to render a cube as an entity, or how to render a model on the screen yet.

```
I'm too lazy to write the code that these libraries provide and they're open
source so here's the licenses.

NOTE: you're gonna wanna use Ctrl-F or grep or / or something to find stuff
in here rather than scrolling because some licenses are just straight up C
header files because I couldn't be bothered to do anything fancier with my
janky CMake script to generate this file.
```
the language is too informal.
```
All of the code provided is open source, as is the status of all of Purpl's
dependencies at the time of writing. Please note that you some of the
applicable licenses are inside of the C header files.
```

An example game directory, with a repository with an asset being imported in the game and entity logic being implanted. If you would upload some sort of test game to github that would answer a lot of the questions I have with engine.

thirdpartylegalnotices.txt is mostly `dirent.h for windows` I think the algorithm glitched up

**Comment by MobSlicer152** [comment]
There's no rendering yet. It hasn't been implemented. The informal language is simply a choice.

**Comment by thomas992** [comment]
I think the game engine is worth sharing with a lot of people. Expand your perceived audience like the whole world wants Purpl.
